using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GameCreator.Framework
{
    public class KeyCodes
    {
        public static readonly string[] Names = new string[] {
        #region Values
            "<no key>",
            "<any key>",
            null,
            null,
            null,
            null,
            null,
            null,
            "<Backspace>",
            "<Tab>",
            null,
            null,
            null,
            "<Enter>",
            null,
            null,
            "<Shift>",
            "<Ctrl>",
            "<Alt>",
            "<Pause>",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "<Escape>",
            null,
            null,
            null,
            null,
            "<Space>",
            "<Page Up>",
            "<Page Down>",
            "<End>",
            "<Home>",
            "<Left>",
            "<Up>",
            "<Right>",
            "<Down>",
            null,
            null,
            null,
            "<Print Screen>",
            "<Insert>",
            "<Delete>",
            null,
            "0-key",
            "1-key",
            "2-key",
            "3-key",
            "4-key",
            "5-key",
            "6-key",
            "7-key",
            "8-key",
            "9-key",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "A-key",
            "B-key",
            "C-key",
            "D-key",
            "E-key",
            "F-key",
            "G-key",
            "H-key",
            "I-key",
            "J-key",
            "K-key",
            "L-key",
            "M-key",
            "N-key",
            "O-key",
            "P-key",
            "Q-key",
            "R-key",
            "S-key",
            "T-key",
            "U-key",
            "V-key",
            "W-key",
            "X-key",
            "Y-key",
            "Z-key",
            null,
            null,
            null,
            null,
            null,
            "Keypad 0",
            "Keypad 1",
            "Keypad 2",
            "Keypad 3",
            "Keypad 4",
            "Keypad 5",
            "Keypad 6",
            "Keypad 7",
            "Keypad 8",
            "Keypad 9",
            "Keypad *",
            "Keypad +",
            null,
            "Keypad -",
            "Keypad .",
            "Keypad /",
            "F1",
            "F2",
            "F3",
            "F4",
            "F5",
            "F6",
            "F7",
            "F8",
            "F9",
            "F10",
            "F11",
            "F12",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "<Left Shift>",
            "<Right Shift>",
            "<Left Ctrl>",
            "<Right Ctrl>",
            "<Left Alt>",
            "<Right Alt>",
        #endregion
        };
    }
}
